version: '3.1'

services:

  backend:
    image: backend
    build:
      context: .
      dockerfile: docker/Dockerfile-backend
    volumes:
      - ./data:/data
    ports:
      - 8000:8000
      - 127.0.0.1:9000:9000
  
  frontend:
    image: frontend
    links:
      - backend
    build:
      context: .
      dockerfile: docker/Dockerfile-frontend
    ports:
      - 8080:8080
